// utils/countryData.js
export const countries = [
    { name: "Afghanistan", code: "+93", length: 9, regex: /^\d{9}$/ },
    { name: "Albania", code: "+355", length: 9, regex: /^\d{9}$/ },
    { name: "Algeria", code: "+213", length: 9, regex: /^\d{9}$/ },
    { name: "Andorra", code: "+376", length: 6, regex: /^\d{6}$/ },
    { name: "Angola", code: "+244", length: 9, regex: /^\d{9}$/ },
    { name: "Argentina", code: "+54", length: 10, regex: /^\d{10}$/ },
    { name: "Armenia", code: "+374", length: 8, regex: /^\d{8}$/ },
    { name: "Australia", code: "+61", length: 9, regex: /^\d{9}$/ },
    { name: "Austria", code: "+43", length: 10, regex: /^\d{10}$/ },
    { name: "Azerbaijan", code: "+994", length: 9, regex: /^\d{9}$/ },
    { name: "Bahamas", code: "+1-242", length: 10, regex: /^\d{10}$/ },
    { name: "Bahrain", code: "+973", length: 8, regex: /^\d{8}$/ },
    { name: "Bangladesh", code: "+880", length: 10, regex: /^\d{10}$/ },
    { name: "Belgium", code: "+32", length: 9, regex: /^\d{9}$/ },
    { name: "Bhutan", code: "+975", length: 8, regex: /^\d{8}$/ },
    { name: "Bolivia", code: "+591", length: 8, regex: /^\d{8}$/ },
    { name: "Bosnia and Herzegovina", code: "+387", length: 8, regex: /^\d{8}$/ },
    { name: "Brazil", code: "+55", length: 11, regex: /^\d{10,11}$/ },
    { name: "Bulgaria", code: "+359", length: 9, regex: /^\d{9}$/ },
    { name: "Cambodia", code: "+855", length: 9, regex: /^\d{9}$/ },
    { name: "Cameroon", code: "+237", length: 9, regex: /^\d{9}$/ },
    { name: "Canada", code: "+1", length: 10, regex: /^\d{10}$/ },
    { name: "Chile", code: "+56", length: 9, regex: /^\d{9}$/ },
    { name: "China", code: "+86", length: 11, regex: /^\d{11}$/ },
    { name: "Colombia", code: "+57", length: 10, regex: /^\d{10}$/ },
    { name: "Congo", code: "+242", length: 9, regex: /^\d{9}$/ },
    { name: "Costa Rica", code: "+506", length: 8, regex: /^\d{8}$/ },
    { name: "Croatia", code: "+385", length: 9, regex: /^\d{9}$/ },
    { name: "Cuba", code: "+53", length: 8, regex: /^\d{8}$/ },
    { name: "Cyprus", code: "+357", length: 8, regex: /^\d{8}$/ },
    { name: "Czech Republic", code: "+420", length: 9, regex: /^\d{9}$/ },
    { name: "Denmark", code: "+45", length: 8, regex: /^\d{8}$/ },
    { name: "Egypt", code: "+20", length: 10, regex: /^\d{10}$/ },
    { name: "Estonia", code: "+372", length: 8, regex: /^\d{8}$/ },
    { name: "Ethiopia", code: "+251", length: 9, regex: /^\d{9}$/ },
    { name: "Finland", code: "+358", length: 10, regex: /^\d{10}$/ },
    { name: "France", code: "+33", length: 9, regex: /^\d{9}$/ },
    { name: "Germany", code: "+49", length: 11, regex: /^\d{10,11}$/ },
    { name: "Ghana", code: "+233", length: 9, regex: /^\d{9}$/ },
    { name: "Greece", code: "+30", length: 10, regex: /^\d{10}$/ },
    { name: "Hong Kong", code: "+852", length: 8, regex: /^\d{8}$/ },
    { name: "Hungary", code: "+36", length: 9, regex: /^\d{9}$/ },
    { name: "Iceland", code: "+354", length: 7, regex: /^\d{7}$/ },
    { name: "India", code: "+91", length: 10, regex: /^\d{10}$/ },
    { name: "Indonesia", code: "+62", length: 10, regex: /^\d{10}$/ },
    { name: "Iran", code: "+98", length: 10, regex: /^\d{10}$/ },
    { name: "Iraq", code: "+964", length: 10, regex: /^\d{10}$/ },
    { name: "Ireland", code: "+353", length: 9, regex: /^\d{9}$/ },
    { name: "Israel", code: "+972", length: 9, regex: /^\d{9}$/ },
    { name: "Italy", code: "+39", length: 10, regex: /^\d{9,10}$/ },
    { name: "Jamaica", code: "+1-876", length: 10, regex: /^\d{10}$/ },
    { name: "Japan", code: "+81", length: 10, regex: /^\d{10}$/ },
    { name: "Jordan", code: "+962", length: 9, regex: /^\d{9}$/ },
    { name: "Kenya", code: "+254", length: 10, regex: /^\d{10}$/ },
    { name: "Kuwait", code: "+965", length: 8, regex: /^\d{8}$/ },
    { name: "Latvia", code: "+371", length: 8, regex: /^\d{8}$/ },
    { name: "Lebanon", code: "+961", length: 8, regex: /^\d{8}$/ },
    { name: "Lithuania", code: "+370", length: 8, regex: /^\d{8}$/ },
    { name: "Luxembourg", code: "+352", length: 9, regex: /^\d{9}$/ },
    { name: "Malaysia", code: "+60", length: 10, regex: /^\d{9,10}$/ },
    { name: "Mexico", code: "+52", length: 10, regex: /^\d{10}$/ },
    { name: "Morocco", code: "+212", length: 9, regex: /^\d{9}$/ },
    { name: "Nepal", code: "+977", length: 10, regex: /^\d{10}$/ },
    { name: "Netherlands", code: "+31", length: 9, regex: /^\d{9}$/ },
    { name: "New Zealand", code: "+64", length: 9, regex: /^\d{9}$/ },
    { name: "Nigeria", code: "+234", length: 10, regex: /^\d{10}$/ },
    { name: "Norway", code: "+47", length: 8, regex: /^\d{8}$/ },
    { name: "Oman", code: "+968", length: 8, regex: /^\d{8}$/ },
    { name: "Pakistan", code: "+92", length: 10, regex: /^\d{10}$/ },
    { name: "Philippines", code: "+63", length: 10, regex: /^\d{10}$/ },
    { name: "Poland", code: "+48", length: 9, regex: /^\d{9}$/ },
    { name: "Portugal", code: "+351", length: 9, regex: /^\d{9}$/ },
    { name: "Qatar", code: "+974", length: 8, regex: /^\d{8}$/ },
    { name: "Romania", code: "+40", length: 9, regex: /^\d{9}$/ },
    { name: "Russia", code: "+7", length: 10, regex: /^\d{10}$/ },
    { name: "Saudi Arabia", code: "+966", length: 9, regex: /^\d{9}$/ },
    { name: "Singapore", code: "+65", length: 8, regex: /^\d{8}$/ },
    { name: "South Africa", code: "+27", length: 9, regex: /^\d{9}$/ },
    { name: "South Korea", code: "+82", length: 10, regex: /^\d{9,10}$/ },
    { name: "Spain", code: "+34", length: 9, regex: /^\d{9}$/ },
    { name: "Sri Lanka", code: "+94", length: 9, regex: /^\d{9}$/ },
    { name: "Sweden", code: "+46", length: 9, regex: /^\d{9}$/ },
    { name: "Switzerland", code: "+41", length: 9, regex: /^\d{9}$/ },
    { name: "Syria", code: "+963", length: 9, regex: /^\d{9}$/ },
    { name: "Taiwan", code: "+886", length: 9, regex: /^\d{9}$/ },
    { name: "Tanzania", code: "+255", length: 10, regex: /^\d{10}$/ },
    { name: "Thailand", code: "+66", length: 9, regex: /^\d{9}$/ },
    { name: "Turkey", code: "+90", length: 10, regex: /^\d{10}$/ },
    { name: "Uganda", code: "+256", length: 9, regex: /^\d{9}$/ },
    { name: "Ukraine", code: "+380", length: 9, regex: /^\d{9}$/ },
    { name: "United Arab Emirates", code: "+971", length: 9, regex: /^\d{9}$/ },
    { name: "United Kingdom", code: "+44", length: 10, regex: /^7\d{9}$/ },
    { name: "United States", code: "+1", length: 10, regex: /^\d{10}$/ },
    { name: "Uruguay", code: "+598", length: 8, regex: /^\d{8}$/ },
    { name: "Uzbekistan", code: "+998", length: 9, regex: /^\d{9}$/ },
    { name: "Venezuela", code: "+58", length: 10, regex: /^\d{10}$/ },
    { name: "Vietnam", code: "+84", length: 9, regex: /^\d{9}$/ },
    { name: "Yemen", code: "+967", length: 9, regex: /^\d{9}$/ },
    { name: "Zambia", code: "+260", length: 9, regex: /^\d{9}$/ },
    { name: "Zimbabwe", code: "+263", length: 9, regex: /^\d{9}$/ },
];
